# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('expire_at', models.DateTimeField(verbose_name='date expired')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('current_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.Tokens')),
            ],
        ),
    ]
