# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_auto_20170222_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokens',
            old_name='cookie',
            new_name='value',
        ),
    ]
