# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_auto_20170223_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokens',
            old_name='expire_at',
            new_name='expired_at',
        ),
    ]
