# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_auth.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Blogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_auth.Users')),
            ],
        ),
    ]
