# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('size', models.IntegerField()),
                ('times', models.IntegerField(default=0, verbose_name='downloaded times')),
                ('stars', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
