# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='admin_email',
            field=models.CharField(default='qingxuanshabo@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.CharField(default='d14ab2b069', max_length=50, primary_key=True, serialize=False),
        ),
    ]
